In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


# Introduction to tensors
### Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(7)
0
7


In [4]:
#vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [5]:
# MATRIX
MATRIX = torch.tensor([[7, 6],
                       [3, 5]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[1])
print(MATRIX[0])

tensor([[7, 6],
        [3, 5]])
2
torch.Size([2, 2])
tensor([3, 5])
tensor([7, 6])


In [6]:
# TENSORS
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 5, 7],
                        [8, 7, 6]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0][2])

tensor([[[1, 2, 3],
         [3, 5, 7],
         [8, 7, 6]]])
3
torch.Size([1, 3, 3])
tensor([8, 7, 6])


### Random Tensors

Why Random Tensors?

Random tensors are important because the way many neural networkd learn is that they start with tensors full of random numbers & then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [7]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3625, 0.7808, 0.7787, 0.5790],
        [0.3462, 0.2823, 0.1393, 0.9770],
        [0.0941, 0.7823, 0.3094, 0.6097]])

In [8]:
# Create a random tensor with a similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # Height, Width, color channels (R, G, B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [9]:
# creat a tensor of all zeros (AND) ones
zero = torch.zeros(3, 4)
ones = torch.ones(3, 4)
zero, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

### Range of tensors and tensors-like

In [10]:
# use torch.range() or use arange to not get the deprecated message
# range = torch.arange(1, 11)
# range

In [11]:
# creating tensors like
# ten_zeros = torch.zeros_like(range)
# ten_zeros

### Tensor Datatypes

**Note**: Tensor datatypes is one of the three big issues you'll run into with pytorch and deep learning.

1. Tensors not being in the right datatype
2. Tensors not being in the right shape
3. Tensors not on the right device

In [12]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.8, 4.5, 5.2],
                               dtype = torch.float32, # what datatype is the tensor, (e.g. float32 or float16)
                               device=None, # What  device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor operations
float_16_tensor = torch.tensor([4.8, 5.3, 6.4],
                               dtype=torch.float16)
float_16_tensor = float_32_tensor.type(torch.float16)
float_32_tensor.dtype, float_16_tensor

(torch.float32, tensor([3.8008, 4.5000, 5.1992], dtype=torch.float16))

In [13]:
int_32_tensor = torch.tensor([2, 3, 4],
                             dtype=torch.int32)
int_32_tensor * float_16_tensor

tensor([ 7.6016, 13.5000, 20.7969], dtype=torch.float16)

### Getting info from tensors

In [14]:
some_tensor = torch.rand(5, 4)
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape)

tensor([[0.9159, 0.4229, 0.2411, 0.3712],
        [0.0623, 0.9740, 0.0071, 0.9267],
        [0.7214, 0.6743, 0.1295, 0.0993],
        [0.9176, 0.0253, 0.2221, 0.1088],
        [0.9714, 0.8863, 0.1712, 0.4239]])
torch.float32
torch.Size([5, 4])


###Manipulating Tensors (Tensor Operations)

**Tensor Operations Include:**

*   Addition
*   Multiplication (Element-wise)
*   Subtraction
*   Division
*   Matrix Multiplication









In [15]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 10) # -> Addition
print(tensor * 10) # -> Multiplition
print(tensor - 10) # -> subtraction
print(tensor / 10) # -> division

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


In [16]:
# In-build Functions:
print(torch.mul(tensor, 7))
print(torch.add(tensor, 5))

tensor([ 7, 14, 21])
tensor([6, 7, 8])


#### Matrix multiplication

Two main ways of performing multiplication in neural networks and machine learning:

1. Element wise multiplication
2. matrix multiplication (dot product)


1. Element Wise

In [17]:
tensor2 = torch.tensor([3, 6, 8])
print(tensor * tensor2)
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([ 3, 12, 24])


tensor([10, 20, 30])

In [18]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [19]:
# timing

ten =  torch.tensor([1, 2, 3])
value = 0
for i in __builtins__.range(len(ten)): # Use __builtins__.range to refer to the original range function
  value += ten[i] * ten[i]
value

tensor(14)

In [20]:
%%time

torch.mul(tensor, tensor) # took -> 109 µs

CPU times: user 32 µs, sys: 5 µs, total: 37 µs
Wall time: 40.3 µs


tensor([1, 4, 9])

2. Matrix Multiplication also known as dot product

Matrix multiplication (is all you need)

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

**The inner dimensions must match:**

`(3, 2) @ (3, 2)` won't work

`(2, 3) @ (3, 2)` will work

`(3, 2) @ (2, 3)` will work

**The resulting matrix has the shape of the outer dimensions:**

`(2, 3) @ (3, 2) -> (2, 2)`
`(3, 2) @ (2, 3) -> (3, 3)`

Note: "@" in Python is the symbol for matrix multiplication.


In [21]:
torch.matmul(torch.rand(10, 10), torch.rand(10, 10)).shape # the inner dimensions much match
# torch.matmul(torch.rand(10, 10), torch.rand(3, 10)).shape -> error

torch.Size([10, 10])

In [22]:
# shapes for matrix mul

ten_a = torch.tensor([[1, 3],
                      [3, 4],
                      [2, 4]])

ten_b = torch.tensor([[2, 10],
                      [5, 18],
                      [7,  16]])

# torch.mm(ten_a, ten_b)

In [23]:
# to fix perform a transpose, meaning rearrange the tensor

ten_b.T, ten_b

(tensor([[ 2,  5,  7],
         [10, 18, 16]]),
 tensor([[ 2, 10],
         [ 5, 18],
         [ 7, 16]]))

In [24]:
torch.mm(ten_a.T, ten_b).shape, ten_a.T.shape, ten_b.shape

(torch.Size([2, 2]), torch.Size([2, 3]), torch.Size([3, 2]))

## Tensor Agrregation

In [25]:
x = torch.arange(0, 100, 10)
torch.min(x), x.min()

(tensor(0), tensor(0))

In [26]:
x.dtype

torch.int64

In [27]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [28]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # -> cuz mean method does not work with int64

(tensor(45.), tensor(45.))

In [29]:
x.sum()

tensor(450)

### Finding indexes

In [30]:
x.argmin()

tensor(0)

In [31]:
x.argmax()

tensor(9)

## Reshaping, stacking, sqeezing and unsqeezing tensors

`torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().`

`Tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.`

`torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.`

`torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.`

`torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.`

`torch.permute(input, dims)	Returns a view of the original input with its dimensions permuted (rearranged) to dims.`

In [32]:
x = torch.arange(1., 10,)
x.reshape(1, 9), x.reshape(1, 1, 9), x.reshape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]),
 <function Tensor.reshape>)

In [33]:
z = x.view(1, 1, 9)
x, z

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]))

In [34]:
torch.stack([x, x, x, x, x])

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [35]:
x_reshaped = x.reshape(1, 1, 9)
torch.squeeze(x_reshaped), x_reshaped, torch.unsqueeze(x_reshaped, dim=3)

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]),
 tensor([[[[1.],
           [2.],
           [3.],
           [4.],
           [5.],
           [6.],
           [7.],
           [8.],
           [9.]]]]))

In [36]:
x_org = torch.rand(224, 224, 3)

x_premuted = x_org.permute(2, 1, 0)

In [37]:
x_premuted.shape, x_org.shape

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

## Indexing

In [38]:
x = torch.arange(1, 10).reshape(1, 3, 3)


In [39]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [40]:
x[0], x[0, 0], x[0, 1], x[0, 2]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor([4, 5, 6]),
 tensor([7, 8, 9]))

In [41]:
x[0, 0, 0], x[0, 0, 1], x[0, 0, 2]

(tensor(1), tensor(2), tensor(3))

In [42]:
x[0, 1, 0], x[0, 1, 1], x[0, 1, 2]

(tensor(4), tensor(5), tensor(6))

In [43]:
x[0, 2, 0], x[0, 2, 1], x[0, 2, 2]

(tensor(7), tensor(8), tensor(9))

In [44]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [45]:
x[:, 1, 1]

tensor([5])

In [46]:
x[0, 0, :]

tensor([1, 2, 3])

In [47]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [48]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [49]:
x[:, 2, 2]

tensor([9])

In [50]:
x[:,:,0]

tensor([[1, 4, 7]])

In [51]:
import torch
import numpy as np

In [52]:
array = np.arange(0., 10.)
tensor = torch.from_numpy(array)
array, tensor

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [53]:
array = array + 1
tensor, array

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64),
 array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [54]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

## Reproducibility

In [55]:
ran_ten_a = torch.rand(3, 4)
ran_ten_b = torch.rand(3, 4)
print(ran_ten_a == ran_ten_b)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [56]:
RANDOM_SEED = 43
torch.manual_seed(42)
ran_ten_c = torch.rand(3, 4)
torch.manual_seed(42)
ran_ten_d = torch.rand(3, 4)
print(ran_ten_c == ran_ten_d)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [57]:
!nvidia-smi

Fri Nov 28 17:19:42 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   35C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [58]:
torch.cuda.is_available()

True

In [59]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [60]:
torch.cuda.device_count()

1

### using GPU on tensors

In [70]:
tensor = torch.tensor([1, 2, 3])
tensor = tensor.to(device)

In [71]:
tensor

tensor([1, 2, 3], device='cuda:0')

In [72]:
tensor1 = tensor.cpu().numpy()

In [73]:
tensor.device

device(type='cuda', index=0)

In [74]:
tensor.device

device(type='cuda', index=0)