# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
import torch

In [5]:
tensor = torch.rand(7,7)
tensor

tensor([[0.5466, 0.4344, 0.0690, 0.0297, 0.0377, 0.3189, 0.8372],
        [0.4307, 0.1955, 0.1302, 0.8709, 0.3447, 0.2322, 0.9021],
        [0.5989, 0.8449, 0.7857, 0.3930, 0.0548, 0.2726, 0.3397],
        [0.1337, 0.9063, 0.5132, 0.2802, 0.3176, 0.3070, 0.5610],
        [0.0107, 0.5133, 0.0947, 0.3491, 0.3686, 0.6329, 0.2711],
        [0.6241, 0.6239, 0.5129, 0.5892, 0.2826, 0.5770, 0.3322],
        [0.4656, 0.2780, 0.1460, 0.1070, 0.1742, 0.7093, 0.0282]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
ran_tensor = torch.rand(1, 7)

torch.matmul(tensor, ran_tensor.T)


tensor([[0.4493],
        [0.9346],
        [1.0199],
        [0.9405],
        [0.7414],
        [1.1275],
        [0.5460]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [14]:
# torch.random.manual_seed(0)
# ran_1 = torch.rand(7, 7)
# ran_2 = torch.rand(1, 7)


# torch.matmul(ran_1, ran_2.T)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [19]:
torch.cuda.random.manual_seed(1234)
ran_1 = torch.rand(7, 7)
ran_2 = torch.rand(1, 7)


torch.matmul(ran_1, ran_2.T)

tensor([[1.8984],
        [1.4171],
        [1.1102],
        [1.5038],
        [1.7249],
        [1.8912],
        [2.3290]])


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [31]:
torch.random.manual_seed(1234)


print("Device: " + "cuda" if torch.cuda.is_available() else "cpu")

ran_1 = torch.rand(2, 3)
torch.random.manual_seed(1234)
ran_2 = torch.rand(2, 3)

ran_1 = ran_1.to(device='cuda')
ran_2 = ran_2.to(device='cuda')

print(ran_1)
print(ran_2)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [42]:
torch.random.manual_seed(1234)
ran_1 = torch.rand(2, 3)
torch.random.manual_seed(1234)
ran_2 = torch.rand(2, 3)

ran_c = torch.matmul(ran_1, ran_2.T)
ran_c, ran_c.shape


(tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]]),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [44]:
ran_c.max(), ran_c.min()


(tensor(0.6287), tensor(0.2161))

### 9. Find the maximum and minimum index values of the output of 7.

In [45]:
ran_c.argmax(), ran_c.argmin()


(tensor(3), tensor(1))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [49]:
torch.random.manual_seed(7)


r1 = torch.rand(1, 1, 1, 10)


# Remove single dimensions
r1_removed = r1.squeeze()

# Print out tensors and their shapes
print(r1, r1.shape)
print(r1_removed, r1_removed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
